platform :tvos
plugin "cocoapods-expert-difficulty"

target 'classicFilms' do
	#pod "AFNetworking", "~> 3.0"  
	pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking', :branch => '3_0_0_branch'
    pod 'AFNetworking/UIKit', :git => 'https://github.com/AFNetworking/AFNetworking', :branch => '3_0_0_branch'
    
end
